Timesheets test
dyvenia/timesheets pull request #5
Opened 2021-11-12 13:57 UTC by jkrobicki

2021-11-13 07:13 UTC, acivitillo commented
@jkrobicki congrats for your first PR into this project. Here is my feedback:

- you should remove .ipynb files from the source code folders
- review the file names, you have a few filenames like "Untitled"
- remove sqlite databases, databases should not be version controlled
- names like `main_test2.py ` are not good names, please review the file names

2021-11-13 15:13 UTC, jkrobicki commented
@acivitillo, following your feedback I've updated my commit

2021-11-14 09:25 UTC, acivitillo requested changes
in the code, review:

- comments, they need to serve a purpose
- naming conventions, in general `initials` is not a good name, initials of what? What is this function doing? Why do we need this function?

2021-11-14 09:25 UTC, acivitillo commented on backend/main.py
>  # strftime("%m/%d/%Y, %H:%M:%S")
please have a look at the code for comments that can be removed or explained. You do not need to remove comments, but you need to make sure they are easy to understand and they serve a purpose

2021-11-14 09:25 UTC, acivitillo commented on backend/models.py
> +    # @validator('month', always=True, pre=True)
do you need these comments?

2021-11-14 09:25 UTC, acivitillo commented on backend/utils.py
> +def initials(full_name):
what would be a better name for this function?

2021-11-15 16:02 UTC, jkrobicki commented
@acivitillo, I've updated my commit and closed resolved issued

2021-11-16 12:12 UTC, merged